[package]
name = "locate"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "locate"

[dependencies]
fstream = "0.1.2"
walkdir = "2.3.1"
colored = "2.0"